### PR TITLE
Adds test to 'quoted' message PR.

### PR DESCRIPTION
**Pull request by sumanthvrao**
Tests added for e7421af798ada9a6729d5956d0cdeec9865ff9ae.

### CODE REVIEW

**Comment by neiljp** [comment]
@sumanthvrao As per my PM to you, I've merged the first commit with slightly different language, so this PR can refocus on tests :)

**Comment by sumanthvrao** [comment]
@neiljp This has been simplified and 'expected content' is more readable now. The parameters could be placed in a single line (without the need for ''' ), however that's now how the 'raw' html incoming from the server looks like. I have tried to preserve as much of the structure here as possible.

One thing to note here is that, newlines and spaces in the 'raw_html' affect the rendered text.

**Comment by sumanthvrao** [comment]
@neiljp to clarify, do you mean in the tests or in the code (`main_view` of `boxes.py`)?

**Comment by neiljp** [comment]
@sumanthvrao I meant in the code, so the test would be to just test the new method, and you wouldn't then need a lot of setup in the test, since it would be in the new method.

**Comment by sumanthvrao** [comment]
@neiljp All right. I pushed a new commit here which extracts the function based on the point you mentioned above.

**Comment by sumanthvrao** [comment]
@neiljp updated this as per our diccussion on `czo`.

**Comment by amanagr** [comment]
@sumanthvrao It's will be good to have the current behavior as tests. LGTM.

**Comment by neiljp** [comment]
@sumanthvrao Just merged this! :+1: Looking forward to developing these tests further and seeing if we can iron out the few bugs left with quoting :)

**Comment by sumanthvrao** [comment]
great! Glad to have this merged :+1:

**Pull request closed without merging**
