### PR TITLE
Add zulip join chat icon in README, partial fix #26

### LINKED ISSUE #26: TRACKING: Extend user documentation
- [ ] Supported Features
- [x] List of common problems with solution
- [ ] A working demo of ZT. ( An image / video )
- [ ] Why use ZT?
- [ ] How to run on windows? ( urwid uses`fcntl` library which is not available on non-unix platforms.) Recommend using WSL.

### PR DESCRIPTION
**Pull request by kurianbenoy**
partial fix #26

### CODE REVIEW

**Comment by rht** [comment]
@kurianbenoy you should make it specific to the #**zulip-terminal** stream. Check out the badge at https://github.com/zulip/zulip-mobile.

**Comment by amanagr** [comment]
change your commit message to "readme: Add `zuilp: join chat` icon."

**Comment by kurianbenoy** [comment]
Updated the commit message as required

**Comment by amanagr** [comment]
Merged via [ac09dc](https://github.com/zulip/zulip-terminal/commit/ac09dc25a8fbe5978dd8404cfd6de87f9cf72e36). Thanks @kurianbenoy !

**Pull request closed without merging**
