### PR TITLE
requirements: Upgrade urwid_readline to 0.8.

### LINKED ISSUE #177: Test and upgrade uriwdn_readline library to version 0.8
Urwid_readline was recently upgrade to 0.8. Test that it works properly and upgrade the version used in zulip-terminal.

### PR DESCRIPTION
**Pull request by amanagr**
Fixes #177

### CODE REVIEW

**Comment by neiljp** [comment]
@amanagr There are no breaking changes on this upgrade?

**Comment by amanagr** [comment]
It fixes some issues with the arrow keys. It's better to have it, than not.

**Comment by neiljp** [comment]
Sure, just checking if there were any consequences.

Also, I just added a PR for urwid-readline (rr-/urwid_readline#7), since I noticed there was a completion option which we could use, but it requires the completion key be "tab", and in ZT as it stands this is used to cycle between parts of the compose window.

**Comment by amanagr** [comment]
Great! we should definitely work in that direction.

**Pull request merged**
