### PR TITLE
Adds sorting to the user-list fixes #264

### LINKED ISSUE #264: Sort users list alphabetically, independently of capitalisation
Our users list is much better now, but it would be great if we could have the users sorted alphabetically.

This would be useful to have in the next release, but would be a good task for someone newer to zulip-terminal.

While the basic feature implementation is good, appreciated extras could include
* adding tests (using pytest)
* exploring if there are any tricky parts in terms of how to sort different character sets

### PR DESCRIPTION
**Pull request by manpoffc**
Made a minor change in Model.py which sorts the user list under all categories status(active, idle, offline & not active).

fixes #264

Screenshots:

**Before:**
screenshot from 2019-01-22 13-49-45

**After:**
screenshot from 2019-01-22 13-51-55

### CODE REVIEW

**Comment by punchagan** [comment]
@manpoffc Thank you for your contribution! 

- Could you get rid of the pylint stuff from this commit, please? 
- It might be useful to have a test for this.

**Comment by manpoffc** [comment]
@punchagan I've removed the Pylint and now I am working on the test.

**Comment by manpoffc** [comment]
@neiljp yeah its PR to fix #264 issue, I did the required changes as mentioned

**Comment by neiljp** [comment]
@manpoffc Right; do you understand what I meant about the 'fixes' text in the commit text below the title?

**Comment by manpoffc** [comment]
@neiljp  I've added that in the description, do you mean adding it in the commit message?

**Comment by punchagan** [comment]
> Is there a reason for those other changes to the Pipfile?

Those are automatically coming from pylint, I believe. And when I said "pylint stuff", I meant all the changes to the `Pipfile`. 

@manpoffc 
- Remove all the changes to Pylint
- Squash all the changes into a single commit
- Added the Fixes #274 tag to the [commit message]

The [Fixing commits](https://zulip.readthedocs.io/en/latest/git/fixing-commits.html) section of Zulip's Git Guide would be useful reading.

**Comment by manpoffc** [comment]
Yes, those are probably automatic changes.
I'll Squash all the commits and change all the things as mentioned.
@punchagan

**Comment by neiljp** [comment]
@manpoffc You don't normally need the issue in the title of the issue, though that's fine :)

Re the commit 'fixes', that's also normally on a line following the title of the commit; eg. you could have:
```
Sort user list alphabetically with casefold.

Fixes #264 
```

There's a useful zulip document regarding commit styles, but typically we have the file/area, followed by commit+space, description, and ending with a full-stop/period ('.'). You might want to look at existing commit messages using `git log`, `tig`, or exploring the list of commits on github.

**Comment by neiljp** [comment]
@manpoffc Just checking, but are you ready for another review? PR/issue subscribers don't get notified on branch pushes (and they're not always useful anyhow!) so please us know here or on chat.zulip.org #zulip-terminal, if so.

I do see you updated the commit message; note the template I gave in the text, which is a simplified version of the advice given at https://zulip.readthedocs.io/en/latest/contributing/version-control.html#commit-messages - perhaps you can think of a good prefix, if you take a look at previous contributions using `git log` or the tools I mentioned above?

**Comment by neiljp** [comment]
@manpoffc Did you mean to close this before it was merged?

**Comment by neiljp** [comment]
Thanks for working on this @manpoffc :+1: This closed #264 automatically :tada: 
I made a small adjustment to the commit message, but not the code; the commit is here:
https://github.com/zulip/zulip-terminal/commit/5ecc552ad6c1bf4fbb15132179f1ce51138288af

**Pull request closed without merging**
