### PR TITLE
Add functionality to check version from command line

### LINKED ISSUE #280: Add functionality to check version from the command line
`zulip-term --version` should print out the version of the terminal client.

### PR DESCRIPTION
**Pull request by traintraveler**
Prints the version of the terminal client, also prints out the git short hash if on a git version.
Fixes #280

### CODE REVIEW

**Comment by neiljp** [comment]
@traintraveler Did you mean to close this?

**Comment by traintraveler** [comment]
Yes.

**Comment by neiljp** [comment]
@traintraveler You should just have been able to amend the commits and push them to the same branch, which would have made them appear here. You might want to look at the Zulip git guide - most of it is relevant to other projects and use of git too:
https://zulip.readthedocs.io/en/latest/git/index.html

**Comment by traintraveler** [comment]
@neiljp Thanks for that, I'll keep to it from now on.

**Pull request closed without merging**
