### PR TITLE
refactor: Improve naming of stream/topic/user variables in set_count.

### PR DESCRIPTION
**Pull request by sumanthvrao**
This is a follow-up for #8792c64 which makes the variable
names in 'set_count' more descriptive.

* Rename streams -> stream_buttons_log, with iterator stream_button.
* Rename users -> user_buttons_log, with iterator user_button.
* Rename topics -> topic_buttons_log, with iterator topic_button.

### CODE REVIEW

**Comment by sumanthvrao** [comment]
@neiljp Does this follow-up look good?

**Comment by sumanthvrao** [comment]
@amanagr What are your thoughts on renaming these variables in `set_count` function?

**Comment by amanagr** [comment]
LGTM!

**Comment by neiljp** [comment]
@sumanthvrao I just merged this with a slight commit text change - this is an essentially independent commit which stands alone in improving the descriptive nature, and I 'refactored' the text slightly :)

**Comment by neiljp** [comment]
@sumanthvrao As a follow-up, I wonder about changing the `update_count` method to be `update_count_by` with a +/- value rather than an absolute value? That would simplify the code quite substantially? Do we need absolute values at any point? Could we hide the `.count` attribute?

**Comment by sumanthvrao** [comment]
@neiljp That sounds like a good simplification. No, we do not need to absolute values at any point. We could this further in the stream.

**Pull request closed without merging**
