### PR TITLE
tests: Parameterize hard-coded keys used in keypress tests.

### PR DESCRIPTION
**Pull request by preetmishra**
Updated hard-coded keys used in STREAM_MESSAGE, REPLY_AUTHOR, and REPLY_MESSAGE with their respective key parameters.

This solves a part of #533.

### CODE REVIEW

**Comment by neiljp** [comment]
@preetmishra Good catch, though it would have been cleaner in the previous commits ;)

I think this should be the last of these `keypress` issues?

**Comment by preetmishra** [comment]
@neiljp Yes, my bad, it would have been more coherent otherwise.

Yes, I grepped with `keypress` again, this should be the last.

**Comment by neiljp** [comment]
@preetmishra Thanks - now to check for the hard-coding in the code itself, at some point :)

**Comment by preetmishra** [comment]
@neiljp Thanks, on to that now.

**Pull request merged**
