### PR TITLE
requirements: Upgrade pytest to 5.0.1.

### PR DESCRIPTION
**Pull request by amanagr**
This adds many new features to pytest.

### CODE REVIEW

**Comment by amanagr** [comment]
The warnings seem very strange. We will possibly will have to filter them.

**Comment by neiljp** [comment]
I agree we may have to, but there may be alternative options to set (for now) or it could be that things are actually being flagged accurately. The last update of `pytest-pep8` seems some time ago now, which was what made me wonder if we should use zulint or pycodestyle directly.

**Comment by amanagr** [comment]
Agreed, I will remove pytest-pep8 then and add pycodestyle with zulint. I will filter the other warnings.

**Comment by sumanthvrao** [comment]
@amanagr I don't know much about zulint. Would this bring any difference in style compared to how we have stuff currently?

**Comment by amanagr** [comment]
We can customize it to use whatever style we want. :)

**Comment by sumanthvrao** [comment]
Sounds cool! :)

**Comment by neiljp** [comment]
@amanagr See #485. Once that is merged, or before, we can open an issue regarding improving linting, perhaps.

**Comment by neiljp** [comment]
This is superseded by the now-merged #485, as discussed above, so closing now.

**Pull request closed without merging**
