### PR TITLE
[WIP] Better display of tables in notifications

### PR DESCRIPTION
**Pull request by plugyawn**
Adds better formatting for tables in the notifications. WIP for tagging, time, emojis, etc.  

Partial fix for #1174. Discuss at https://chat.zulip.org/#narrow/stream/206-zulip-terminal/topic/Check.20formatting.20of.20markdown.20in.20notifications.20.23T1174.

**Tested?** 
- [x] Manually
- [x] Existing tests (adapted, if necessary)
- [ ] New tests added (for any new behavior)
- [x] Passed linting & tests (each commit)

First commit adds code to reformat the soup, form a text chunk that displays the table properly, and then replace the \<table\> with a \<p\> containing the table's info. 

This does not include improvements for other markdown options. Will add soon.

### CODE REVIEW

**Comment by plugyawn** [comment]
Added aaronsw's https://github.com/aaronsw/html2text script for reformatting the code. Need some help with attribution (and to know if we can actually use his code). Also used regex to fix some issues with emojis. Mostly done. 

Need a LOT of help with linting.

**Comment by plugyawn** [comment]
Added support for bullet lists and emojis. Checked for LaTeX, already works.

**Comment by plugyawn** [comment]
I'll check back with this in a few hours.

**Comment by neiljp** [comment]
See notes in the stream.

**Comment by plugyawn** [comment]
Sorry, missed the stream message. 

I'll address the issues ASAP.

**Comment by neiljp** [comment]
@plugyawn I assume this is replaced by #1207?

**Comment by plugyawn** [comment]
> @plugyawn I assume this is replaced by #1207?

Mostly. #1207 is just for tables, this PR settles a few others, too, but it's messy code. Should I close this?

**Comment by neiljp** [comment]
@plugyawn We can refer back to this later from the other PR and it'll still be searchable generally in any case - and the other changes look fairly small too? Closing this so we can focus on the other PR.

**Comment by plugyawn** [comment]
> @plugyawn We can refer back to this later from the other PR and it'll still be searchable generally in any case - and the other changes look fairly small too? Closing this so we can focus on the other PR.

Okay!

**Pull request closed without merging**
