### PR TITLE
added documentation for quit

### PR DESCRIPTION
**Pull request by vhawk19**
fixed a part of #208

### CODE REVIEW

**Comment by neiljp** [comment]
@vhawk19  Do you plan to add the key to `keys.py` as per #208?

I see you closed two PRs already (with some attempts at the above?) - you can work within the same PR/branch, since you can update the code on your branch and push it again. I would also recommend developing on a different branch than `master` in your local/remote trees.

**Comment by vhawk19** [comment]
Thank for those valuable tips! @neiljp

Actually i tried adding it to keys.py but then the travis build failed and thats why i closed the PR.I am new to Open source contribution which is why i made such rookie mistakes. Sorry!:sweat_smile:

**Comment by neiljp** [comment]
@vhawk19 No problem, we all have to learn somewhere :)

**Comment by vhawk19** [comment]
@neiljp sure, ill try my best to add the change in keys.py and try to build it locally. It would take a couple of days though, having exams😅. If thats fine sure thing.

**Comment by neiljp** [comment]
@vhawk19 No problem, just wanted to check what your plans were - exams are important :)

**Comment by vhawk19** [comment]
I tried to run test locally, but am kind of struggling with it.Is there any guide as to how to run the tests locally?

**Comment by neiljp** [comment]
It depends on your dev setup; if you're using `pipenv` then you can use the current details at
https://github.com/zulip/zulip-terminal#running-tests

If you're running in a manual virtual environment, then activate/enter it and just run `pytest`.

For more interactive help, come chat on the #zulip-terminal channel on chat.zulip.org :)

**Comment by neiljp** [comment]
@vhawk19 Do you need more assistance with this?

**Comment by vhawk19** [comment]
Its just that i am having a real hard time with setting up the test environment. If you could give some guidance about it, it would be really helpful!

**Comment by neiljp** [comment]
@vhawk19 You might find it easier to chat about this on chat.zulip.org, on the #zulip-terminal stream - are you able to access it ok?

**Comment by neiljp** [comment]
Updated documentation is being developed and visible at the following location. Please let us know ASAP if you wish to work on this further, and if those notes are helpful :)
 https://github.com/neiljp/zulip-terminal/tree/expand-dev-env-notes

**Comment by mregdos** [comment]
@neiljp 
@vhawk19 

Out of curiosity (I have only recently managed to install and configure zulip-terminal locally) I have tried to add required changes to keys.py myself ( [code](https://github.com/mregdos/zulip-terminal/commit/98d653adfcd011dc8a84e4af95ebb77af49a7ab8) ). It does work locally (including tests) and on [travis](https://travis-ci.org/mregdos/zulip-terminal/builds/494427578).

Therefore I was slightly confused, since change was basically the same as the one from vhawk19's closed PR (which supposedly caused Travis build to fail) and I tried to understand difference.
It turns out that  blank line containing whitespace was responsible. 

I suggest merging both this pull-request and my newly opened [PR](https://github.com/zulip/zulip-terminal/pull/303) (with keys.py change) in order to fix and close #208 .

**Comment by neiljp** [comment]
This was merged via #306.

**Comment by neiljp** [comment]
@mregdos I'm not sure what the test fail was, but if a test does fail, it is sometimes worth restarting the test on travis, particularly if it is just one, or if they passed without any issues on your local machine.

**Pull request closed without merging**
