### PR TITLE
solarized_dark updated

### PR DESCRIPTION
**Pull request by vipulsaxena31**
**What does this PR do?**  

**Tested?** 
- [ ] Manually
- [ ] Existing tests (adapted, if necessary)
- [ ] New tests added (for any new behavior)
- [ ] Passed linting & tests (each commit)

**Commit flow** 

**Notes & Questions** 

**Interactions** 

**Visual changes**

### CODE REVIEW

**Comment by neiljp** [comment]
@vipulsaxena31 Thanks for looking at this, though this is incomplete right now?

**Comment by vipulsaxena31** [comment]
No it's not

**Comment by neiljp** [comment]
@vipulsaxena31 Do you plan to work on this further?

**Comment by neiljp** [comment]
@vipulsaxena31 Thanks for taking a look at this! Due to multiple PRs I'm closing this in favor of #1345. If you wish to work more with solarized dark then that would be a good PR to build from.

**Pull request closed without merging**
