### PR TITLE
[WIP]boxes: Implement autocomplete for @mention in message box.

### PR DESCRIPTION
**Pull request by ishanrai05**
solves issue #222

### CODE REVIEW

**Comment by ishanrai05** [comment]
@amanagr  can you help me here a bit? Do I have to do something along the lines of this commit or something different?

**Comment by amanagr** [comment]
The issue is basically to implement @mention autocomplete as provided by Zulip Web/ Mobile clients. (Like the one you use on Github. ) 

You will need to first explore how Zulip's webapp does autocompletion and then implement it similarly in ZT. Here is a list of autocomplete code files form Zulip-Mobile if you are interested -> https://github.com/zulip/zulip-mobile/tree/master/src/autocomplete

**Comment by amanagr** [comment]
To clarify, you need to use `urwid_readline` to implement the autocomplete and in the end it should work like as you see in zulip's webapp.

**Comment by neiljp** [comment]
@ishanrai05 You've stopped working on this? We can close this for now?

**Comment by ishanrai05** [comment]
@neiljp  yes.

**Pull request closed without merging**
