### PR TITLE
tools/lister: Remove six dependency

### PR DESCRIPTION
**Pull request by andersk**

### CODE REVIEW

**Comment by neiljp** [comment]
@andersk I can see this is a legacy import that we would never need, except for potentially keeping sync with the originally imported version, but did you use a tool to identify this change or just happen to notice?

**Comment by andersk** [comment]
It was found by [pyupgrade](https://github.com/asottile/pyupgrade/). I wouldn’t have bothered to PR it, except we don’t declare a dependency on `six`, so it could fix an `ImportError`.

**Comment by timabbott** [comment]
@amanagr why do we still have a copy of `lister` in this project?  We should rework this project to just use `zulint` (or `lister` from there, if needed).

**Comment by neiljp** [comment]
@timabbott `lister` is used by the current version of `run-mypy` - which zulip now imports from `zulint`. We haven't fully discussed next stages to integrate zulint, but see #508 & #528.

I was looking at the dependencies, and while some dev dependencies require it - so it shouldn't be an issue for an install, currently, assuming those don't change - apparently `zulip` depends on it still too? While ZT doesn't depend on the latest version, even that still has dependencies upon `six`, according to the package:
https://pypi.org/project/zulip/

So, see #zulip/python-zulip-api#597 for a remedy for the `zulip` issue.

**Comment by neiljp** [comment]
I was leaving this tiny PR open for responses, but will merge it now, thanks @andersk :+1: Feel free to comment on the zulint issues/pulls or discuss elsewhere.

**Pull request merged**
