### PR TITLE
Updated the AboutView popup with Exit confirmation setting

### PR DESCRIPTION
**Pull request by rsashank**
Tests updated.

### What does this PR do, and why?
Added the Exit confirmation setting to the AboutView popup.

### Outstanding aspect(s)    

- [ ] 

### External discussion & connections

- [ ] Discussed in **#zulip-terminal** in `topic`
- [ ] Fully fixes #
- [ ] Partially fixes issue #
- [ ] Builds upon previous unmerged work in PR #
- [x] Is a follow-up to work in PR #1432
- [ ] Requires merge of PR #
- [ ] Merge will enable work on #

### How did you test this?

- [ ] Manually - Behavioral changes
- [x] Manually - Visual changes
- [x] Adapting existing automated tests
- [x] Adding automated tests for new behavior (or missing tests)
- [ ] Existing automated tests should already cover this (*only a refactor of tested code*)

### Self-review checklist for each commit
- [x] It is a [minimal coherent idea](https://github.com/zulip/zulip-terminal#structuring-commits---speeding-up-reviews-merging--development)
- [x] It has a commit summary following the [documented style](https://github.com/zulip/zulip-terminal#structuring-commits---speeding-up-reviews-merging--development) (title & body)
- [ ] It has a commit summary describing the  motivation and reasoning for the change
- [x] It individually passes linting and tests
- [x] It contains test additions for any new behavior
- [x] It flows clearly from a previous branch commit, and/or prepares for the next commit

### CODE REVIEW

**Comment by rsashank** [comment]
I think I might require some guidance here, I'm uncertain about the reason for the failure. I successfully run all tests on my local Pop!_OS machine.

Additionally, my forked repository is encountering issues with the `GitHub CodeQL/Analyse (push)` despite having being synced.

**Comment by rsashank** [comment]
@zulipbot add PR needs review

**Comment by rsashank** [comment]
@zulipbot help

**Comment by rsashank** [comment]
@zulipbot add "PR needs review"

**Comment by neiljp** [comment]
@rsashank Thanks for this update following the other PR - this looks great to merge :+1:

**Pull request merged**
