### PR TITLE
ZT redesign UI layout for stream and user search boxes

### PR DESCRIPTION
**Pull request by sumanthvrao**
This tweaks the UI layout my making th following adjustments
* Avoids top border line in user and stream search box
* Rewords the search message in MessageSearch Box to extend to `Search messages: `
* Extend the top-left and top-right borders of central message view to make them look more vertical
redesign_UI_layout

### CODE REVIEW

**Comment by neiljp** [comment]
As discussed on the stream, other than seeing more consensus on whether this seems like a slightly cleaner look overall, I think we should also think about the colon (`:`) in the message pane - possibly remove it?

**Comment by sumanthvrao** [comment]
Discussion continued https://chat.zulip.org/#narrow/stream/206-zulip-terminal/topic/Redesign.20Search.20bar.20.26.20msg.20box/near/761496

**Comment by neiljp** [comment]
@sumanthvrao Thanks for getting this idea implemented :+1: As per the discussions on czo I've merged the line changes, but not the textual commit.

I'll close this, since I think we should discuss how to unify the search box designs, and possibly track that via an issue. That could involve updating how we handle the message search, to make the most of space.

**Comment by neiljp** [comment]
#413 is a follow-up to this, which adds some thicker lines to emphasize each column title.

**Pull request closed without merging**
