### PR TITLE
Indicate message year, when it is not the current year

### PR DESCRIPTION
**Pull request by neiljp**
This is a fix for #470, has tests, and works functionally for me. Feedback welcome.

I propose that the extension ideas in #470 are placed into other issues, for things such as any styling improvements and potentially dynamic date changes as with the webapp.

### CODE REVIEW

**Comment by amanagr** [comment]
LGTM, I am not sure about the star change that @sumanthvrao suggested.

**Comment by neiljp** [comment]
@sumanthvrao I agree about the star looking odd. The first commit does resolve the issue, but I just added another if you'd like to try that.

@amanagr See how you like the star repositioning.

Perhaps long-term we could place the star next to the message.

**Comment by sumanthvrao** [comment]
@neiljp The star repositioning looks good. :+1:

**Comment by neiljp** [comment]
Merging now, given the positive review and feedback.

**Pull request merged**
