### PR TITLE
Translation of developer feature tutorial to pt_BR

### PR DESCRIPTION
**Pull request by felipecpassos**
**What does this PR do?**

Added translation for developer feature tutorial documentation in pt_BR (Brazil).

**Tested?** 
- [X] Manually
- [X] Existing tests (adapted, if necessary)
- [X] New tests added (for any new behavior)
- [X] Passed linting & tests (each commit)

**Commit flow** 

**Notes & Questions**

### CODE REVIEW

**Comment by neiljp** [comment]
@felipecpassos Thanks for this - did you translate this manually?

We don't have documentation translations in the terminal documentation, so I'm not sure of the best practice for handling translations like this. If it would have been useful to you then that provides a good starting point of course :) My main concern is keeping things synchronized if we update documents, and how far things go before we definitely need to update (or even remove) the translations due to inaccuracy.

**Comment by felipecpassos** [comment]
Yes i did it manually :sweat_smile: 

The synchronization issue is really a problem, and i can't think of a way to solve it.
I had my doubts about the usefulness of this PR, because there was no other translated file.

I made this for a assignment in a class in Software Engineering, and you can discard if it has no use (not a lot of Brazilians in zulip terminal community i believe). 

Sorry for the time taken to review this PR.

**Comment by neiljp** [comment]
@felipecpassos No problem, thanks for working on it! Maybe the wider Zulip community has more information on translations of this kind of document.

**Comment by zormit** [comment]
Considering the discussion above and the age, I think this PR can be closed.

**Comment by neiljp** [comment]
@zormit Agreed, this seems sensible at this point :+1:

@felipecpassos Thanks for your work on this in any case! I'm unsure if you're using or otherwise involved in Zulip, but you might consider the translations in the apps with translations if you've not already - or for ourselves when we add that! Thanks again!

**Pull request closed without merging**
