### PR TITLE
Updated README with screenshot 

### LINKED ISSUE #286: Add Screenshots / GIF on README.md
I think it would be helpful for new users to have screenshots/GIFs on the main README file to demonstrate how the app looks and behaves. This gives new/potential users a quick glance at what they would get if they went through the signup/download/install process.

### PR DESCRIPTION
**Pull request by shreyamalviya**
Fixes #286

### CODE REVIEW

**Comment by shreyamalviya** [comment]
@neiljp, yes, I'm working on it. I'll keep you updated.

**Comment by neiljp** [comment]
@shreyamalviya Have you paused work on this?

**Comment by shreyamalviya** [comment]
I was having trouble setting up the development server. How am I supposed to log in to the dev server from ZT?
Sorry for not being more prompt.

**Comment by sumanthvrao** [comment]
@shreyamalviya You can download the `zuliprc` file for the respective user accounts (from web-app) (Eg: Iago, Prospero, other users....). You can then use `zulip-term -c /path/to/zuliprc` to log into those from ZT. If you have any setup related issues regarding development server, you can ask it in #development-help.

**Comment by neiljp** [comment]
@shreyamalviya I was mainly wanting to find out if you were still interested or working on it, in case anyone else starts on it. As I posted on #z-t, the dev server approach could be a second stage - since we have nothing on github right now, any kind of detail (that isn't too big) would be a good first step :)

**Comment by shreyamalviya** [comment]
@neiljp, alright, so should I just add a screenshot of czo like before?

**Comment by shreyamalviya** [comment]
@neiljp, updated.

**Comment by som23ya** [comment]
hey is there anymore work left on this issue or issue #286 ? still open?

**Comment by neiljp** [comment]
@shreyamalviya This was from some time ago now; would you like to update this or leave #286 to someone else?

@som23ya Sorry to miss your question, but this is still open, but wasn't reviewed over the Summer.

**Comment by shreyamalviya** [comment]
@som23ya, hi! You can go ahead and work on this. I don't plan on doing it anytime soon. Good luck!

**Comment by preetmishra** [comment]
Thanks for your time and effort, everyone! This has been fixed in 63156539d7373fefe329f5afc9e2e5c484e467df. :tada:

**Pull request closed without merging**
