### PR TITLE
docker: fix locale setting in Debian Buster Dockerfile.

### PR DESCRIPTION
**Pull request by fredrikekre**
Fixes the locale issue mentioned in https://github.com/zulip/zulip-terminal/issues/797#issue-707661389.

### CODE REVIEW

**Comment by fredrikekre** [comment]
Ah, just noted that the same ENV var is set in #571 and looks like the answer to https://github.com/zulip/zulip-terminal/pull/571#discussion_r419318527 is "Yes".

**Comment by neiljp** [comment]
@fredrikekre Thanks for this - this makes the buster build work for you, I assume?

I'm aware you didn't have this issue with the other dockerfile, but do you think we want it in both dockerfiles?

While this may fix the issue for you, my concern is that this would pin the locale too far (ie. we basically lose all localization with `C`?). However, if users can override `ENV` when running the image, or of course adjust the docker file, it seems more important to get this working first. That said does setting `LANG` instead fix this?

@sumanthvrao Given you added this to #571, do you have thoughts on these points?

**Comment by fredrikekre** [comment]
> this makes the buster build work for you, I assume?

Yes.

> do you think we want it in both dockerfiles?

Not sure, given that it works without it seems unnecessary to add it, and from my very limited research, it seems like musl libc handles locales in a somewhat different way, so this fix might not even be applicable.

> That said does setting `LANG` instead fix this?

Doesn't look like it.

---

I have to say that I didn't really do any extensive research about this. I dug into this a bit more, and I found https://github.com/urwid/urwid/commit/fd010f8336407ad1a42522b424d2ea7b7800ebc4 which likely fixes this (the call to [`locale.setlocale`](https://github.com/urwid/urwid/blob/4c739b6be21b0c98324e7b7780d8e712f3ad6db3/urwid/util.py#L59) is what throws, but that error is now [caught](https://github.com/urwid/urwid/blob/4c739b6be21b0c98324e7b7780d8e712f3ad6db3/urwid/util.py#L60). https://github.com/urwid/urwid/commit/fd010f8336407ad1a42522b424d2ea7b7800ebc4 is in [urwid@2.1.2](https://github.com/urwid/urwid/releases/tag/release-2.1.2) (tagged 2 hours ago, what a timing!), so this PR is probably redundant when upgrading urwid.

**Comment by fredrikekre** [comment]
Closing in favor of upgrading urvid.

**Pull request closed without merging**
