### PR TITLE
themes: Add new styles to incomplete themes.

### PR DESCRIPTION
**Pull request by ishanrai05**
This PR adds new styles and completes the light theme and the blue theme.

`test-theme` has also been updated to include both light and blue themes in list of completed themes.

**Screenshots:**
Light Theme:
sslight

Blue Theme:
ssblue

solves issue #254

### CODE REVIEW

**Comment by amanagr** [comment]
Thanks @ishanrai05 for working on this! Looks fine to me, but I would wait for @neiljp to have his final thoughts on this.

**Comment by rht** [comment]
> but I'm not sure whether github will complain that the first commit already closed the issue

Why not let it be and see what happens? (Though what is most likely to happen is that the next commits will be ignored in favor of the first one.)

IMO the PR as it is, is already fine to merge. As in, better have a complete the first, then fix the color synergy.

**Comment by amanagr** [comment]
@neiljp sounds reasonable to me. Also, I don't think there is a problem with merging with two separate commits closing the issue.

**Comment by neiljp** [comment]
@ishanrai05 To clarify, if you can tidy the commit text that would be sufficient to merge the commits, though we will want to look at the styling soon after.

**Comment by ishanrai05** [comment]
I'll make the required changes asap. :) thank you for reviewing this. @neiljp

**Comment by amanagr** [comment]
LGTM now :)

**Pull request merged**
